[tool.isort]
line_length = 79
known_future_library = ["future", "pies"]
known_third_party = []
indent = "    "
multi_line_output= 3
include_trailing_comma= "True"
force_grid_wrap= 0
use_parentheses= "True"

[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml"